/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author 16494634-7
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    EstadosCiviles ec;
    FichaCliente fc;
    Impresion im;
    Activacion ac;
    IngresoEjecutivo ie;
    Documentos dc;
    
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jmIngresoEjComercial = new javax.swing.JMenuItem();
        jmIngresoEjOperaciones = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jmFichaCliente = new javax.swing.JMenuItem();
        jmModificarCliente = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmImpresionContrato = new javax.swing.JMenuItem();
        jmImpresionPlastico = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmAprobarCredito = new javax.swing.JMenuItem();
        jmRechazarCredito = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmActivacionTarjeta = new javax.swing.JMenuItem();
        jmActivacionPin = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jmEstadoCivil = new javax.swing.JMenuItem();
        jmModificarEstCivil = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmAdjuntarDocumentos = new javax.swing.JMenuItem();
        jmEliminarDocumentos = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jmIngresarCargos = new javax.swing.JMenuItem();
        jmModificarCargos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\David\\Desktop\\Metalizado l.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 720, 340);

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu5.setText("Ejecutivo");

        jmIngresoEjComercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmIngresoEjComercial.setText("Ingreso Ej. Comercial");
        jmIngresoEjComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIngresoEjComercialActionPerformed(evt);
            }
        });
        jMenu5.add(jmIngresoEjComercial);

        jmIngresoEjOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmIngresoEjOperaciones.setText("Ingreso Ej. Operaciones");
        jmIngresoEjOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIngresoEjOperacionesActionPerformed(evt);
            }
        });
        jMenu5.add(jmIngresoEjOperaciones);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem19.setText("Salir");
        jMenu5.add(jMenuItem19);

        jMenuBar1.add(jMenu5);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu1.setText("Postulación");

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu10.setText("Cliente Nuevo");

        jmFichaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmFichaCliente.setText("Ingresar Cliente");
        jmFichaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFichaClienteActionPerformed(evt);
            }
        });
        jMenu10.add(jmFichaCliente);

        jmModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmModificarCliente.setText("Modificar  Cliente");
        jMenu10.add(jmModificarCliente);

        jMenu1.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu11.setText("Cliente Registrado");

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem21.setText("Modificar  Cliente");
        jMenu11.add(jMenuItem21);

        jMenu1.add(jMenu11);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmSalir.setText("Salir");
        jMenu1.add(jmSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu2.setText("Impresión");

        jmImpresionContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmImpresionContrato.setText("Impresión Contrato");
        jmImpresionContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImpresionContratoActionPerformed(evt);
            }
        });
        jMenu2.add(jmImpresionContrato);

        jmImpresionPlastico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmImpresionPlastico.setText("Impresión Plastico");
        jmImpresionPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImpresionPlasticoActionPerformed(evt);
            }
        });
        jMenu2.add(jmImpresionPlastico);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem11.setText("Salir");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu3.setText("Evaluación");

        jmAprobarCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmAprobarCredito.setText("Aprobar Crédito");
        jMenu3.add(jmAprobarCredito);

        jmRechazarCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmRechazarCredito.setText("Rechazar Crédito");
        jMenu3.add(jmRechazarCredito);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem14.setText("Salir");
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu4.setText("Activación");

        jmActivacionTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmActivacionTarjeta.setText("Activación Tarjeta");
        jmActivacionTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActivacionTarjetaActionPerformed(evt);
            }
        });
        jMenu4.add(jmActivacionTarjeta);

        jmActivacionPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmActivacionPin.setText("Activación PIN");
        jmActivacionPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActivacionPinActionPerformed(evt);
            }
        });
        jMenu4.add(jmActivacionPin);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem17.setText("Salir");
        jMenu4.add(jMenuItem17);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu6.setText("Parametros");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu7.setText("Estado Civil");

        jmEstadoCivil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmEstadoCivil.setText("Ingresar Estado Civil");
        jmEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadoCivilActionPerformed(evt);
            }
        });
        jMenu7.add(jmEstadoCivil);

        jmModificarEstCivil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmModificarEstCivil.setText("Modificar Estado Civil");
        jmModificarEstCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarEstCivilActionPerformed(evt);
            }
        });
        jMenu7.add(jmModificarEstCivil);

        jMenu6.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu8.setText("Documentos");

        jmAdjuntarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmAdjuntarDocumentos.setText("Adjuntar Documentos");
        jmAdjuntarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdjuntarDocumentosActionPerformed(evt);
            }
        });
        jMenu8.add(jmAdjuntarDocumentos);

        jmEliminarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmEliminarDocumentos.setText("Eliminar Documentos");
        jmEliminarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarDocumentosActionPerformed(evt);
            }
        });
        jMenu8.add(jmEliminarDocumentos);

        jMenu6.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu9.setText("Cargos");

        jmIngresarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmIngresarCargos.setText("Ingresar Cargos");
        jMenu9.add(jmIngresarCargos);

        jmModificarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jmModificarCargos.setText("Modificar Cargos");
        jMenu9.add(jmModificarCargos);

        jMenu6.add(jMenu9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 716, 381);
    }// </editor-fold>//GEN-END:initComponents

    private void jmEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadoCivilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ec = new EstadosCiviles();
        ec.setVisible(true);
    }//GEN-LAST:event_jmEstadoCivilActionPerformed

    private void jmFichaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFichaClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fc = new FichaCliente();
        fc.setVisible(true);
    }//GEN-LAST:event_jmFichaClienteActionPerformed

    private void jmImpresionContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImpresionContratoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        im = new Impresion();
        im.setVisible(true);
    }//GEN-LAST:event_jmImpresionContratoActionPerformed

    private void jmImpresionPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImpresionPlasticoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        im = new Impresion();
        im.setVisible(true);
    }//GEN-LAST:event_jmImpresionPlasticoActionPerformed

    private void jmActivacionTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActivacionTarjetaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ac = new Activacion();
        ac.setVisible(true);
    }//GEN-LAST:event_jmActivacionTarjetaActionPerformed

    private void jmActivacionPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActivacionPinActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ac = new Activacion();
        ac.setVisible(true);
    }//GEN-LAST:event_jmActivacionPinActionPerformed

    private void jmIngresoEjComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIngresoEjComercialActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ie = new IngresoEjecutivo();
        ie.setVisible(true);
    }//GEN-LAST:event_jmIngresoEjComercialActionPerformed

    private void jmIngresoEjOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIngresoEjOperacionesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ie = new IngresoEjecutivo();
        ie.setVisible(true);
    }//GEN-LAST:event_jmIngresoEjOperacionesActionPerformed

    private void jmModificarEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarEstCivilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ec = new EstadosCiviles();
        ec.setVisible(true);
    }//GEN-LAST:event_jmModificarEstCivilActionPerformed

    private void jmAdjuntarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdjuntarDocumentosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dc = new Documentos();
        dc.setVisible(true);
    }//GEN-LAST:event_jmAdjuntarDocumentosActionPerformed

    private void jmEliminarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarDocumentosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dc = new Documentos();
        dc.setVisible(true);
    }//GEN-LAST:event_jmEliminarDocumentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jmActivacionPin;
    private javax.swing.JMenuItem jmActivacionTarjeta;
    private javax.swing.JMenuItem jmAdjuntarDocumentos;
    private javax.swing.JMenuItem jmAprobarCredito;
    private javax.swing.JMenuItem jmEliminarDocumentos;
    private javax.swing.JMenuItem jmEstadoCivil;
    private javax.swing.JMenuItem jmFichaCliente;
    private javax.swing.JMenuItem jmImpresionContrato;
    private javax.swing.JMenuItem jmImpresionPlastico;
    private javax.swing.JMenuItem jmIngresarCargos;
    private javax.swing.JMenuItem jmIngresoEjComercial;
    private javax.swing.JMenuItem jmIngresoEjOperaciones;
    private javax.swing.JMenuItem jmModificarCargos;
    private javax.swing.JMenuItem jmModificarCliente;
    private javax.swing.JMenuItem jmModificarEstCivil;
    private javax.swing.JMenuItem jmRechazarCredito;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
