/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author David
 */
public class MenuInicioG extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicioG
     */
    public MenuInicioG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Metalizado l.jpg"))); // NOI18N

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu5.setText("Administrar Usuarios");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu1.setText("Crear Ejecutivo");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem2.setText("Ejecutivo Comercial");
        jMenu1.add(jMenuItem2);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem18.setText("Ejecutivo Operaciones");
        jMenu1.add(jMenuItem18);

        jMenu5.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu2.setText("Asignar Usuario");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem4.setText("Ejecutivo Comercial");
        jMenu2.add(jMenuItem4);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem22.setText("Ejecutivo Operaciones");
        jMenu2.add(jMenuItem22);

        jMenu5.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu3.setText("Asignar Clave");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem5.setText("Ejecutivo Comercial");
        jMenu3.add(jMenuItem5);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem23.setText("Ejecutivo Operaciones");
        jMenu3.add(jMenuItem23);

        jMenu5.add(jMenu3);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem19.setText("Salir");
        jMenu5.add(jMenuItem19);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu6.setText("Administrar Clientes");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu4.setText("Ficha Cliente");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem3.setText("Modificar Cliente");
        jMenu4.add(jMenuItem3);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem20.setText("Eliminar Cliente");
        jMenu4.add(jMenuItem20);

        jMenu6.add(jMenu4);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenu7.setText("Crédito Cliente");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem6.setText("Aprueba Cliente");
        jMenu7.add(jMenuItem6);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem24.setText("Cliente");
        jMenu7.add(jMenuItem24);

        jMenu6.add(jMenu7);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoQ.png"))); // NOI18N
        jMenuItem21.setText("Salir");
        jMenu6.add(jMenuItem21);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicioG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicioG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicioG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicioG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicioG().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
